version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:3456/Final_project"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "3456:3456"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
